import { useState, ChangeEvent } from 'react';
import { ChevronLeft, Rocket, Info, Wand2 } from 'lucide-react';
import { createCampaign, publishCampaign } from '../api';
import toast from 'react-hot-toast';
import confetti from 'canvas-confetti';
import { CampaignFormData } from '../types';

interface CampaignFormProps {
  onCancel: () => void;
  onSuccess: () => void;
}

export default function CampaignForm({ onCancel, onSuccess }: CampaignFormProps) {
  const [formData, setFormData] = useState<CampaignFormData>({
    name: '',
    objective: 'TRAFFIC',
    campaign_type: 'Demand Gen',
    daily_budget: 10,
    start_date: new Date().toISOString().split('T')[0],
    end_date: '',
    ad_group_name: '',
    ad_headline: '',
    ad_description: '',
    asset_url: ''
  });

  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);

  const handleChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const value = e.target.type === 'number' ? parseFloat(e.target.value) : e.target.value;
    setFormData({ ...formData, [e.target.name]: value });
  };

  const handleGenerateCopy = () => {
     if (!formData.name) {
        toast.error("Please enter a Campaign Name first to generate context.");
        return;
     }
     
     setGenerating(true);
     
     // Simulate AI Latency
     setTimeout(() => {
        const keywords = formData.name.split(' ');
        const product = keywords[0] || 'Product';
        
        const headlines = [
           `Best ${product} Deals`,
           `Shop ${product} Online`,
           `Premium ${product} - 20% Off`,
           `${product} for Professionals`
        ];
        
        const descriptions = [
           `Discover the best ${product} at unbeatable prices. Shop now and save big on your first order.`,
           `Upgrade your lifestyle with our premium ${product}. Limited time offer, free shipping available.`,
           `Don't miss out on our exclusive ${product} collection. High quality, great value.`
        ];
        
        setFormData(prev => ({
           ...prev,
           ad_headline: headlines[Math.floor(Math.random() * headlines.length)],
           ad_description: descriptions[Math.floor(Math.random() * descriptions.length)],
           ad_group_name: `${product} - High Intent`,
           asset_url: `https://example.com/shop/${product.toLowerCase()}`
        }));
        
        toast.success("Ad copy generated by AI ✨");
        setGenerating(false);
     }, 1000);
  };

  const handleSubmit = async (publishNow = false) => {
    // Validation
    if (formData.end_date && formData.start_date && formData.end_date < formData.start_date) {
        toast.error("End date cannot be before start date");
        return;
    }

    setSaving(true);
    const toastId = toast.loading(publishNow ? 'Creating & Publishing...' : 'Saving Draft...');
    
    try {
      // 1. Create Local
      const res = await createCampaign(formData);
      const campaignId = res.data.id;

      // 2. Publish if requested
      if (publishNow) {
        toast.loading('Pushing to Google Ads...', { id: toastId });
        await publishCampaign(campaignId);
        confetti({
          particleCount: 150,
          spread: 70,
          origin: { y: 0.6 }
        });
      }

      toast.success(publishNow ? 'Campaign Live!' : 'Draft Saved!', { id: toastId });
      
      // Delay to show success state before closing
      setTimeout(() => {
        onSuccess();
      }, 1000);

    } catch (error: any) {
      toast.error("Error: " + (error.response?.data?.error || error.message), { id: toastId });
      setSaving(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto animate-fade-in pb-20">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <button onClick={onCancel} className="p-2 hover:bg-white/5 rounded-full text-text-secondary hover:text-white transition">
           <ChevronLeft size={24} />
        </button>
        <div>
          <h2 className="text-2xl font-bold">New Campaign</h2>
          <p className="text-text-secondary text-sm">Configure your campaign settings for Google Ads</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Form */}
        <div className="lg:col-span-2 space-y-6">
          
          <Section title="Campaign Settings">
             <div className="space-y-4">
                <div className="">
                  <label className="block text-sm font-medium text-text-secondary mb-1">Campaign Name</label>
                  <input 
                    className="input-field" 
                    name="name" 
                    value={formData.name} 
                    onChange={handleChange} 
                    placeholder="e.g. Summer Sale 2025"
                    required 
                  />
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                   <div>
                    <label className="block text-sm font-medium text-text-secondary mb-1">Objective</label>
                    <div className="relative">
                      <select className="input-field appearance-none" name="objective" value={formData.objective} onChange={handleChange}>
                        <option value="TRAFFIC">Website Traffic</option>
                        <option value="SALES">Sales</option>
                        <option value="LEADS">Leads</option>
                        <option value="BRAND_AWARENESS">Brand Awareness</option>
                      </select>
                      <div className="absolute right-3 top-3 pointer-events-none text-text-secondary">
                        <ChevronLeft size={16} className="-rotate-90" />
                      </div>
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-text-secondary mb-1">Type</label>
                     <div className="relative">
                       <select className="input-field appearance-none" name="campaign_type" value={formData.campaign_type} onChange={handleChange}>
                        <option value="Demand Gen">Demand Gen (Discovery)</option>
                        <option value="Search">Search</option>
                        <option value="Display">Display</option>
                       </select>
                       <div className="absolute right-3 top-3 pointer-events-none text-text-secondary">
                        <ChevronLeft size={16} className="-rotate-90" />
                      </div>
                     </div>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-text-secondary mb-1">Start Date</label>
                    <input type="date" className="input-field" name="start_date" value={formData.start_date} onChange={handleChange} />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-text-secondary mb-1">End Date</label>
                    <input type="date" className="input-field" name="end_date" value={formData.end_date} onChange={handleChange} />
                  </div>
                </div>
             </div>
          </Section>

          <Section title="Ad Creative">
             <div className="flex justify-between items-center mb-4 border-b border-white/5 pb-2">
                <h3 className="text-lg font-semibold">Ad Creative</h3>
                <button 
                  onClick={handleGenerateCopy}
                  disabled={generating}
                  className="text-xs flex items-center gap-1.5 text-purple-400 hover:text-purple-300 transition-colors bg-purple-500/10 px-2 py-1 rounded-full border border-purple-500/20"
                >
                  <Wand2 size={12} />
                  {generating ? 'Generating...' : 'Auto-Generate'}
                </button>
             </div>
             <div className="space-y-4">
               <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">Ad Group Name</label>
                  <input className="input-field" name="ad_group_name" value={formData.ad_group_name} onChange={handleChange} placeholder="e.g. Hero Section Ads" />
               </div>
               
               <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">Headline</label>
                  <input className="input-field" name="ad_headline" value={formData.ad_headline} onChange={handleChange} maxLength={30} placeholder="Max 30 chars" />
                  <div className="text-right text-xs text-text-muted mt-1">{formData.ad_headline.length}/30</div>
               </div>

               <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">Description</label>
                  <textarea className="input-field" name="ad_description" value={formData.ad_description} onChange={handleChange} maxLength={90} rows={3} placeholder="Max 90 chars"></textarea>
                  <div className="text-right text-xs text-text-muted mt-1">{formData.ad_description.length}/90</div>
               </div>
               
               <div>
                  <label className="block text-sm font-medium text-text-secondary mb-1">Final URL</label>
                  <input className="input-field" name="asset_url" value={formData.asset_url} onChange={handleChange} type="url" placeholder="https://" />
               </div>
             </div>
          </Section>

        </div>

        {/* Sidebar */}
        <div className="space-y-6">
           <div className="card p-5 sticky top-24">
              <h3 className="font-semibold text-lg mb-4">Ad Preview</h3>
              {/* Google Search Preview Card */}
              <div className="bg-white p-3 rounded mb-6 select-none cursor-default font-sans text-left">
                  <div className="flex items-center gap-1 mb-1">
                      <span className="font-bold text-black text-xs">Ad</span>
                      <span className="text-xs text-gray-500">•</span>
                      <span className="text-xs text-gray-600 truncate max-w-[150px]">{formData.asset_url || 'example.com'}</span>
                  </div>
                  <div className="text-[#1a0dab] text-lg leading-6 cursor-pointer hover:underline mb-1">
                      {formData.ad_headline || 'Your Ad Headline Here'}
                  </div>
                  <div className="text-sm text-[#4d5156] leading-5">
                      {formData.ad_description || 'Your ad description will appear here. Highlight your product features and benefits to attract customers.'}
                  </div>
              </div>

              <h3 className="font-semibold text-lg mb-4">Budgeting & Bidding</h3>
              <div className="mb-4">
                <label className="block text-sm font-medium text-text-secondary mb-2">Daily Budget</label>
                <div className="relative">
                   <div className="absolute left-3 top-3 text-text-secondary">$</div>
                   <input 
                      type="number" 
                      className="input-field pl-8" 
                      name="daily_budget" 
                      value={formData.daily_budget} 
                      onChange={handleChange}
                    />
                </div>
              </div>

               <div className="mb-4">
                <label className="block text-sm font-medium text-text-secondary mb-2">Bidding Strategy</label>
                <div className="relative">
                  <select 
                     className="input-field appearance-none" 
                     name="bidding_strategy" 
                     value={formData.bidding_strategy || 'MAXIMIZE_CONVERSIONS'} 
                     onChange={handleChange}
                  >
                     <option value="MAXIMIZE_CONVERSIONS">Maximize Conversions</option>
                     <option value="TARGET_CPA">Target CPA</option>
                     <option value="MAXIMIZE_CLICKS">Maximize Clicks</option>
                  </select>
                   <div className="absolute right-3 top-3 pointer-events-none text-text-secondary">
                        <ChevronLeft size={16} className="-rotate-90" />
                   </div>
                </div>
              </div>

              {formData.bidding_strategy === 'TARGET_CPA' && (
                 <div className="mb-4 animate-fade-in-up">
                  <label className="block text-sm font-medium text-text-secondary mb-2">Target CPA</label>
                  <div className="relative">
                     <div className="absolute left-3 top-3 text-text-secondary">$</div>
                     <input 
                        type="number" 
                        className="input-field pl-8" 
                        name="target_cpa" 
                        value={formData.target_cpa || ''} 
                        onChange={handleChange}
                        placeholder="5.00"
                      />
                  </div>
                </div>
              )}
              
              <div className="bg-blue-500/10 p-3 rounded-md text-sm text-blue-200 mb-6 flex gap-2">
                 <Info size={16} className="shrink-0 mt-0.5" />
                 <span>Estimated monthly spend: <br/><strong>${formData.daily_budget * 30}</strong></span>
              </div>

              <div className="flex flex-col gap-3">
                 <button 
                  className="btn btn-primary w-full justify-between" 
                  onClick={() => handleSubmit(true)}
                  disabled={saving}
                 >
                   <span>Publish Campaign</span>
                   <Rocket size={18} />
                 </button>
                 <button 
                  className="btn btn-secondary w-full" 
                  onClick={() => handleSubmit(false)}
                  disabled={saving}
                 >
                   Save as Draft
                 </button>
              </div>
           </div>
        </div>

      </div>
    </div>
  );
}

function Section({ title, children }: { title: string, children: React.ReactNode }) {
  return (
    <div className="card p-6">
      <h3 className="text-lg font-semibold mb-4 border-b border-white/5 pb-2">{title}</h3>
      {children}
    </div>
  )
}
